### PR TITLE
use existing gitlab config template

### PR DESCRIPTION
**Pull request by tuxmea**
@alvagante is it ok to merge this to production?

### CODE REVIEW

**Comment by alvagante** [comment]
@tuxmea nope, the generic one handles the options_hash entries which are not currently parametrized in the one you are placing in this pr. Reason for this change?

**Comment by tuxmea** [comment]
there is no generic template in psick for gitlab.

**Comment by alvagante** [comment]
The one you are trying to use is very static and has almost no variables placehoders, so, as is, it's basicaally useless (it was initially added for quick setup: https://github.com/example42/puppet-psick/blob/master/templates/gitlab/gitlab.rb.erb)

The generic one exists and allows any variable defined in the options hash, pus the required external_url setting: https://github.com/example42/puppet-psick/blob/master/templates/gitlab/gitlab.rb-generic.erb

So I'd not merge this PR

**Comment by tuxmea** [comment]
hm I wonder why I have not seen the file.... closing PR

**Pull request closed without merging**
